#:schema node_modules/wrangler/config-schema.json
name = "persist-cf-render-worker"
main = "src/index.js"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]

browser = { binding = "BROWSER" }

[[r2_buckets]]
binding = "PERSIST_BUCKET"
bucket_name = "hlte-persistence"
preview_bucket_name = "hlte-persistence"

[[kv_namespaces]]
binding = "KV_STORE"
id = "ba6796c74c8c443abf0879cc8979c87a"
preview_id = "ba6796c74c8c443abf0879cc8979c87a"